### ISSUE TITLE
Add tutorial mode

### ISSUE THREAD

**Issue by Djkcool** [antimundo/libre-aim#12]
Add a separate tutorial mode that explains and shows the user how to play each of the game modes to avoid confusion.

**Comment by antimundo** [comment]
Not sure how I would implement this feature, or if it should be implemented at all. I prefer to improve the UX and make things more clear, instead of making a "tutorial". At least now, so early in the development.

**Comment by dfgworm** [comment]
Yeah, don't know what a tutorial would even do. It would literally just tell the user to move their mouse to aim, and maybe tell them to aim at the target. Such tutorial in general is a questionable thing.
In this particular case i would argue that if user doesn't even know how to aim, they probably don't need this trainer at all.
