### ISSUE TITLE
Cool Project

### ISSUE THREAD

**Issue by rysllvn** [antimundo/libre-aim#13]
Minor issue. 

When I loaded up a game mode my screen panned to the right steadily. It's probably due to some flight sim hardware I have plugged in. For myself, it is no issue and I just commented out `_handle_joypad_rotation(delta)` in `player_manager.gd`.

I thought you might want to know though. Thanks for sharing the project.

**Comment by antimundo** [comment]
Thanks for the feedback! Maby we could add a feature to disable joypad movement, to avoid problems like yours.

I'm starting to think about creating a Discord Server or something like that for people like you that wants to provide small feedback and talk about the project.
