### ISSUE TITLE
Expose sensitivity setting as slider

### ISSUE THREAD

**Issue by ThePat02** [antimundo/libre-aim#15]
Problem: Right now the sense setting is hidden away in a small easy to miss text box that even excepts letters.

Proposal: Move the setting down and allow the user to use a slider in addition to a numeral text input.

**Comment by antimundo** [comment]
I actually just changed this yesterday in 04bc5c4e076a9e4707b0267b4892375bc27776e0 take a look,

Now there is indeed a slider and a number text input.
