### ISSUE TITLE
Load custom resources into the game

### ISSUE THREAD

**Issue by antimundo** [antimundo/libre-aim#24]
Related to #19 and #20 

Currently there are some settings that are loaded dinamically. But if you export the project there is no way for a user to add more of these files, and this should be an option.

Currently, the `user://data/highscores.cfg` and `user://data/settings.cfg` store the player save data. So let's keep going in that direction and save custom resources this way:
- Target hit sound under: `user://data/hit_sounds/examplesound.ogg`
- World appareance texture: `user://data/world_appareance/exampletexture.png`
- Custom gamemodes: `user://data/gamemodes/examplegamemode.cfg`

Those files should be loaded when LibreAim opens, let's worry about how this folder structure is dinamically created, and how those files are loaded when a user opens LibreAim. Let's asume for the moment that players are expected to close LibreAim and open it again in order to load the custom files they added.

**Comment by dfgworm** [comment]
'data' folder is for DataManager, which specifically uses ConfigFile class and is used to store simple data entries with support for default values. I would even suggest different name for the service, but ConfigManager sounds like a weird place to store data like highscores.

I wouldn't put more pressure on this singleton or on this folder. This feature sounds completely unrelated, deserving it's own service and folder, like CustomResourceManager using 'resources' folder. It would be able to handle sounds, images and check for files in specific directiories.
